[2025-04-02T06:22:11.556+0000] {processor.py:186} INFO - Started process (PID=7899) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T06:22:11.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T06:22:11.565+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:22:11.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T06:22:11.626+0000] {logging_mixin.py:190} INFO - [2025-04-02T06:22:11.617+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T06:22:11.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T06:22:11.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.124 seconds
[2025-04-02T09:06:41.863+0000] {processor.py:186} INFO - Started process (PID=7965) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T09:06:41.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T09:06:41.870+0000] {logging_mixin.py:190} INFO - [2025-04-02T09:06:41.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T09:06:41.918+0000] {logging_mixin.py:190} INFO - [2025-04-02T09:06:41.907+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T09:06:41.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T09:06:41.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.114 seconds
[2025-04-02T11:03:37.676+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:03:37.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:03:37.682+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:03:37.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:03:37.754+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:03:37.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:03:37.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:03:37.799+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.132 seconds
[2025-04-02T11:04:08.599+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:04:08.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:04:08.608+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:04:08.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:04:08.681+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:04:08.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:04:08.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:04:08.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.134 seconds
[2025-04-02T11:04:39.207+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:04:39.209+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:04:39.214+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:04:39.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:04:39.258+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:04:39.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:04:39.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:04:39.289+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.088 seconds
[2025-04-02T11:05:10.106+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:05:10.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:05:10.113+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:05:10.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:05:10.152+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:05:10.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:05:10.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:05:10.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.090 seconds
[2025-04-02T11:05:41.028+0000] {processor.py:186} INFO - Started process (PID=296) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:05:41.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:05:41.034+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:05:41.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:05:41.084+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:05:41.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:05:41.087+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:05:41.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.100 seconds
[2025-04-02T11:06:11.578+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:06:11.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:06:11.587+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:06:11.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:06:11.633+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:06:11.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:06:11.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:06:11.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.105 seconds
[2025-04-02T11:06:41.853+0000] {processor.py:186} INFO - Started process (PID=426) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:06:41.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:06:41.862+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:06:41.861+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:06:41.913+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:06:41.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:06:41.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:06:41.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.104 seconds
[2025-04-02T11:07:12.777+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:07:12.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:07:12.786+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:07:12.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:07:12.837+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:07:12.827+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:07:12.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:07:12.876+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.107 seconds
[2025-04-02T11:07:43.490+0000] {processor.py:186} INFO - Started process (PID=556) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:07:43.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:07:43.497+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:07:43.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:07:43.562+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:07:43.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:07:43.564+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:07:43.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.111 seconds
[2025-04-02T11:08:14.451+0000] {processor.py:186} INFO - Started process (PID=621) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:08:14.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:08:14.459+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:08:14.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:08:14.505+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:08:14.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:08:14.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:08:14.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.092 seconds
[2025-04-02T11:08:45.080+0000] {processor.py:186} INFO - Started process (PID=686) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:08:45.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:08:45.089+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:08:45.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:08:45.139+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:08:45.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:08:45.142+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:08:45.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.122 seconds
[2025-04-02T11:09:16.247+0000] {processor.py:186} INFO - Started process (PID=751) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:09:16.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:09:16.255+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:09:16.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:09:16.296+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:09:16.288+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:09:16.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:09:16.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.092 seconds
[2025-04-02T11:09:46.612+0000] {processor.py:186} INFO - Started process (PID=816) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:09:46.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:09:46.621+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:09:46.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:09:46.670+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:09:46.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:09:46.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:09:46.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.102 seconds
[2025-04-02T11:10:17.700+0000] {processor.py:186} INFO - Started process (PID=881) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:10:17.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:10:17.708+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:10:17.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:10:17.756+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:10:17.749+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:10:17.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:10:17.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.096 seconds
[2025-04-02T11:10:48.102+0000] {processor.py:186} INFO - Started process (PID=946) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:10:48.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:10:48.110+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:10:48.110+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:10:48.157+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:10:48.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:10:48.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:10:48.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.092 seconds
[2025-04-02T11:11:18.666+0000] {processor.py:186} INFO - Started process (PID=1011) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:11:18.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:11:18.675+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:11:18.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:11:18.728+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:11:18.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:11:18.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:11:18.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.113 seconds
[2025-04-02T11:11:49.490+0000] {processor.py:186} INFO - Started process (PID=1082) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:11:49.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:11:49.497+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:11:49.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:11:49.530+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:11:49.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:11:49.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:11:49.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.076 seconds
[2025-04-02T11:12:19.933+0000] {processor.py:186} INFO - Started process (PID=1147) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:12:19.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:12:19.939+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:12:19.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:12:19.972+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:12:19.965+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:12:19.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:12:20.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.081 seconds
[2025-04-02T11:12:50.443+0000] {processor.py:186} INFO - Started process (PID=1213) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:12:50.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:12:50.452+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:12:50.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:12:50.491+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:12:50.481+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:12:50.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:12:50.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.093 seconds
[2025-04-02T11:13:21.399+0000] {processor.py:186} INFO - Started process (PID=1278) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:13:21.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:13:21.406+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:13:21.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:13:21.448+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:13:21.439+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:13:21.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:13:21.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.084 seconds
[2025-04-02T11:13:51.757+0000] {processor.py:186} INFO - Started process (PID=1343) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:13:51.760+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:13:51.764+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:13:51.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:13:51.795+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:13:51.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:13:51.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:13:51.819+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.075 seconds
[2025-04-02T11:14:22.873+0000] {processor.py:186} INFO - Started process (PID=1408) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:14:22.876+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:14:22.882+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:14:22.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:14:22.933+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:14:22.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:14:22.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:14:22.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.112 seconds
[2025-04-02T11:14:53.399+0000] {processor.py:186} INFO - Started process (PID=1473) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:14:53.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:14:53.407+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:14:53.406+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:14:53.454+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:14:53.445+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:14:53.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:14:53.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.103 seconds
[2025-04-02T11:15:24.525+0000] {processor.py:186} INFO - Started process (PID=1538) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:15:24.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:15:24.535+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:15:24.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:15:24.591+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:15:24.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:15:24.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:15:24.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.122 seconds
[2025-04-02T11:15:55.090+0000] {processor.py:186} INFO - Started process (PID=1603) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:15:55.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:15:55.096+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:15:55.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:15:55.145+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:15:55.135+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:15:55.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:15:55.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.106 seconds
[2025-04-02T11:16:25.339+0000] {processor.py:186} INFO - Started process (PID=1668) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:16:25.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:16:25.346+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:16:25.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:16:25.395+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:16:25.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:16:25.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:16:25.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.102 seconds
[2025-04-02T11:16:56.220+0000] {processor.py:186} INFO - Started process (PID=1733) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:16:56.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:16:56.231+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:16:56.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:16:56.281+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:16:56.273+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:16:56.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:16:56.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.110 seconds
[2025-04-02T11:17:27.197+0000] {processor.py:186} INFO - Started process (PID=1798) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:17:27.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:17:27.205+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:17:27.204+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:17:27.253+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:17:27.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:17:27.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:17:27.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.097 seconds
[2025-04-02T11:17:58.095+0000] {processor.py:186} INFO - Started process (PID=1863) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:17:58.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:17:58.102+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:17:58.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:17:58.175+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:17:58.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 2, in <module>
    from langchain_core.prompts import ChatPromptTemplate
ModuleNotFoundError: No module named 'langchain_core'
[2025-04-02T11:17:58.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:17:58.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.120 seconds
[2025-04-02T11:18:29.239+0000] {processor.py:186} INFO - Started process (PID=1928) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:18:29.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:18:29.247+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:18:29.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:18:29.297+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:18:29.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 2, in <module>
    from langchain_core.prompts import ChatPromptTemplate
ModuleNotFoundError: No module named 'langchain_core'
[2025-04-02T11:18:29.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:18:29.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.102 seconds
[2025-04-02T11:18:59.993+0000] {processor.py:186} INFO - Started process (PID=1993) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:18:59.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:19:00.003+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:19:00.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:19:00.056+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:19:00.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 2, in <module>
    from langchain_core.prompts import ChatPromptTemplate
ModuleNotFoundError: No module named 'langchain_core'
[2025-04-02T11:19:00.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:19:00.091+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.108 seconds
[2025-04-02T11:19:19.114+0000] {processor.py:186} INFO - Started process (PID=2030) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:19:19.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:19:19.119+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:19:19.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:19:19.174+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:19:19.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import  pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 2, in <module>
    from langchain_core.prompts import ChatPromptTemplate
ModuleNotFoundError: No module named 'langchain_core'
[2025-04-02T11:19:19.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:19:19.212+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.104 seconds
[2025-04-02T11:19:50.084+0000] {processor.py:186} INFO - Started process (PID=2095) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:19:50.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:19:50.091+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:19:50.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:19:50.138+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:19:50.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import  pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 2, in <module>
    from langchain_core.prompts import ChatPromptTemplate
ModuleNotFoundError: No module named 'langchain_core'
[2025-04-02T11:19:50.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:19:50.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.097 seconds
[2025-04-02T11:20:05.920+0000] {processor.py:186} INFO - Started process (PID=2148) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:20:05.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:20:05.924+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:20:05.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:20:05.965+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:20:05.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 2, in <module>
    from langchain_core.prompts import ChatPromptTemplate
ModuleNotFoundError: No module named 'langchain_core'
[2025-04-02T11:20:05.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:20:05.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.072 seconds
[2025-04-02T11:20:36.181+0000] {processor.py:186} INFO - Started process (PID=2213) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:20:36.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:20:36.189+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:20:36.188+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:20:36.277+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:20:36.269+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:20:36.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:20:36.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.137 seconds
[2025-04-02T11:21:06.537+0000] {processor.py:186} INFO - Started process (PID=2279) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:21:06.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:21:06.544+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:21:06.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:21:06.581+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:21:06.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:21:06.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:21:06.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.081 seconds
[2025-04-02T11:21:36.737+0000] {processor.py:186} INFO - Started process (PID=2344) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:21:36.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:21:36.743+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:21:36.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:21:36.775+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:21:36.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:21:36.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:21:36.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.069 seconds
[2025-04-02T11:22:07.105+0000] {processor.py:186} INFO - Started process (PID=2406) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:22:07.108+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:22:07.119+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:22:07.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:22:07.175+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:22:07.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:22:07.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:22:07.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.135 seconds
[2025-04-02T11:22:37.555+0000] {processor.py:186} INFO - Started process (PID=2472) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:22:37.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:22:37.562+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:22:37.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:22:37.605+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:22:37.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:22:37.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:22:37.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.098 seconds
[2025-04-02T11:23:08.049+0000] {processor.py:186} INFO - Started process (PID=2537) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:23:08.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:23:08.059+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:23:08.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:23:08.107+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:23:08.097+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:23:08.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:23:08.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.113 seconds
[2025-04-02T11:23:39.025+0000] {processor.py:186} INFO - Started process (PID=2602) to work on /opt/airflow/dags/pipeline1.py
[2025-04-02T11:23:39.027+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-02T11:23:39.032+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:23:39.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:23:39.109+0000] {logging_mixin.py:190} INFO - [2025-04-02T11:23:39.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-02T11:23:39.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-02T11:23:39.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.142 seconds
