[2025-04-01T17:59:14.850+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T17:59:14.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T17:59:14.856+0000] {logging_mixin.py:190} INFO - [2025-04-01T17:59:14.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T17:59:14.901+0000] {logging_mixin.py:190} INFO - [2025-04-01T17:59:14.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 5, in <module>
    from models.database import connect_to_db, disconnect_from_db, sql_to_dataframe
ModuleNotFoundError: No module named 'models'
[2025-04-01T17:59:14.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T17:59:14.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.090 seconds
[2025-04-01T17:59:45.271+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T17:59:45.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T17:59:45.280+0000] {logging_mixin.py:190} INFO - [2025-04-01T17:59:45.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T17:59:45.305+0000] {logging_mixin.py:190} INFO - [2025-04-01T17:59:45.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 5, in <module>
    from models.database import connect_to_db, disconnect_from_db, sql_to_dataframe
ModuleNotFoundError: No module named 'models'
[2025-04-01T17:59:45.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T17:59:45.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.095 seconds
[2025-04-01T18:00:16.302+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:00:16.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:00:16.312+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:00:16.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:00:16.338+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:00:16.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 5, in <module>
    from models.database import connect_to_db, disconnect_from_db, sql_to_dataframe
ModuleNotFoundError: No module named 'models'
[2025-04-01T18:00:16.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:00:16.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.086 seconds
[2025-04-01T18:00:47.219+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:00:47.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:00:47.229+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:00:47.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:00:47.247+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:00:47.242+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 5, in <module>
    from models.database import connect_to_db, disconnect_from_db, sql_to_dataframe
ModuleNotFoundError: No module named 'models'
[2025-04-01T18:00:47.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:00:47.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.087 seconds
[2025-04-01T18:01:17.866+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:01:17.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:01:17.872+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:01:17.872+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:01:17.887+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:01:17.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 5, in <module>
    from models.database import connect_to_db, disconnect_from_db, sql_to_dataframe
ModuleNotFoundError: No module named 'models'
[2025-04-01T18:01:17.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:01:17.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.054 seconds
[2025-04-01T18:01:48.753+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:01:48.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:01:48.761+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:01:48.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:01:48.781+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:01:48.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 5, in <module>
    from models.database import connect_to_db, disconnect_from_db, sql_to_dataframe
ModuleNotFoundError: No module named 'models'
[2025-04-01T18:01:48.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:01:48.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.083 seconds
[2025-04-01T18:02:19.164+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:02:19.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:02:19.172+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:02:19.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:02:19.187+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:02:19.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 5, in <module>
    from models.database import connect_to_db, disconnect_from_db, sql_to_dataframe
ModuleNotFoundError: No module named 'models'
[2025-04-01T18:02:19.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:02:19.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.069 seconds
[2025-04-01T18:02:49.310+0000] {processor.py:186} INFO - Started process (PID=490) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:02:49.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:02:49.317+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:02:49.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:02:49.459+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:02:49.452+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:02:49.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:02:49.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.191 seconds
[2025-04-01T18:03:19.961+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:03:19.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:03:19.970+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:03:19.969+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:03:20.121+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:03:20.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:03:20.123+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:03:20.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.200 seconds
[2025-04-01T18:03:50.223+0000] {processor.py:186} INFO - Started process (PID=621) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:03:50.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:03:50.229+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:03:50.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:03:50.285+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:03:50.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:03:50.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:03:50.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.106 seconds
[2025-04-01T18:04:21.073+0000] {processor.py:186} INFO - Started process (PID=685) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:04:21.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:04:21.082+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:04:21.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:04:21.129+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:04:21.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:04:21.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:04:21.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.104 seconds
[2025-04-01T18:04:51.781+0000] {processor.py:186} INFO - Started process (PID=750) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:04:51.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:04:51.789+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:04:51.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:04:51.841+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:04:51.830+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:04:51.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:04:51.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.123 seconds
[2025-04-01T18:05:22.422+0000] {processor.py:186} INFO - Started process (PID=815) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:05:22.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:05:22.430+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:05:22.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:05:22.476+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:05:22.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:05:22.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:05:22.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.109 seconds
[2025-04-01T18:05:52.780+0000] {processor.py:186} INFO - Started process (PID=880) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:05:52.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:05:52.791+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:05:52.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:05:52.841+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:05:52.833+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:05:52.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:05:52.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.122 seconds
[2025-04-01T18:06:23.493+0000] {processor.py:186} INFO - Started process (PID=945) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:06:23.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:06:23.504+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:06:23.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:06:23.555+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:06:23.548+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:06:23.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:06:23.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.111 seconds
[2025-04-01T18:06:54.079+0000] {processor.py:186} INFO - Started process (PID=1010) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:06:54.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:06:54.091+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:06:54.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:06:54.151+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:06:54.140+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:06:54.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:06:54.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.120 seconds
[2025-04-01T18:07:24.266+0000] {processor.py:186} INFO - Started process (PID=1075) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:07:24.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:07:24.274+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:07:24.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:07:24.314+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:07:24.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:07:24.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:07:24.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.099 seconds
[2025-04-01T18:07:54.442+0000] {processor.py:186} INFO - Started process (PID=1140) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:07:54.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:07:54.449+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:07:54.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:07:54.487+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:07:54.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:07:54.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:07:54.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.095 seconds
[2025-04-01T18:08:25.264+0000] {processor.py:186} INFO - Started process (PID=1205) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:08:25.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:08:25.273+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:08:25.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:08:25.314+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:08:25.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:08:25.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:08:25.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.096 seconds
[2025-04-01T18:08:55.551+0000] {processor.py:186} INFO - Started process (PID=1271) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:08:55.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:08:55.559+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:08:55.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:08:55.600+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:08:55.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:08:55.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:08:55.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.093 seconds
[2025-04-01T18:09:26.154+0000] {processor.py:186} INFO - Started process (PID=1336) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:09:26.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:09:26.164+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:09:26.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:09:26.202+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:09:26.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:09:26.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:09:26.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.093 seconds
[2025-04-01T18:09:56.745+0000] {processor.py:186} INFO - Started process (PID=1402) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:09:56.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:09:56.753+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:09:56.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:09:56.793+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:09:56.785+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:09:56.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:09:56.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.084 seconds
[2025-04-01T18:10:27.744+0000] {processor.py:186} INFO - Started process (PID=1467) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:10:27.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:10:27.753+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:10:27.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:10:27.794+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:10:27.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:10:27.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:10:27.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.114 seconds
[2025-04-01T18:10:57.946+0000] {processor.py:186} INFO - Started process (PID=1532) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:10:57.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:10:57.955+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:10:57.954+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:10:57.997+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:10:57.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:10:57.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:10:58.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.095 seconds
[2025-04-01T18:11:28.257+0000] {processor.py:186} INFO - Started process (PID=1597) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:11:28.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:11:28.262+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:11:28.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:11:28.294+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:11:28.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:11:28.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:11:28.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.073 seconds
[2025-04-01T18:11:58.464+0000] {processor.py:186} INFO - Started process (PID=1663) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:11:58.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:11:58.472+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:11:58.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:11:58.508+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:11:58.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:11:58.511+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:11:58.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.087 seconds
[2025-04-01T18:12:29.224+0000] {processor.py:186} INFO - Started process (PID=1728) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:12:29.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:12:29.237+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:12:29.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:12:29.290+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:12:29.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:12:29.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:12:29.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.116 seconds
[2025-04-01T18:13:00.199+0000] {processor.py:186} INFO - Started process (PID=1799) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:13:00.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:13:00.207+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:13:00.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:13:00.255+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:13:00.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:13:00.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:13:00.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.113 seconds
[2025-04-01T18:13:30.473+0000] {processor.py:186} INFO - Started process (PID=1864) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:13:30.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:13:30.480+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:13:30.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:13:30.514+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:13:30.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:13:30.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:13:30.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.087 seconds
[2025-04-01T18:14:00.875+0000] {processor.py:186} INFO - Started process (PID=1929) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:14:00.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:14:00.883+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:14:00.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:14:00.928+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:14:00.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:14:00.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:14:00.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.096 seconds
[2025-04-01T18:14:31.059+0000] {processor.py:186} INFO - Started process (PID=1997) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:14:31.061+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:14:31.065+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:14:31.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:14:31.094+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:14:31.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:14:31.095+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:14:31.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.064 seconds
[2025-04-01T18:15:01.807+0000] {processor.py:186} INFO - Started process (PID=2062) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:15:01.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:15:01.816+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:15:01.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:15:01.870+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:15:01.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:15:01.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:15:01.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.146 seconds
[2025-04-01T18:15:32.807+0000] {processor.py:186} INFO - Started process (PID=2127) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:15:32.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:15:32.814+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:15:32.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:15:32.855+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:15:32.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:15:32.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:15:32.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.092 seconds
[2025-04-01T18:16:03.291+0000] {processor.py:186} INFO - Started process (PID=2192) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:16:03.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:16:03.299+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:16:03.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:16:03.339+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:16:03.330+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:16:03.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:16:03.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.096 seconds
[2025-04-01T18:16:33.616+0000] {processor.py:186} INFO - Started process (PID=2257) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:16:33.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:16:33.626+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:16:33.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:16:33.670+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:16:33.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:16:33.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:16:33.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.104 seconds
[2025-04-01T18:17:04.246+0000] {processor.py:186} INFO - Started process (PID=2322) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:17:04.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:17:04.251+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:17:04.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:17:04.283+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:17:04.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:17:04.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:17:04.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.072 seconds
[2025-04-01T18:17:35.144+0000] {processor.py:186} INFO - Started process (PID=2387) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:17:35.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:17:35.148+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:17:35.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:17:35.182+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:17:35.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:17:35.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:17:35.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.080 seconds
[2025-04-01T18:18:06.068+0000] {processor.py:186} INFO - Started process (PID=2452) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:18:06.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:18:06.074+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:18:06.074+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:18:06.124+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:18:06.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:18:06.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:18:06.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.108 seconds
[2025-04-01T18:18:36.273+0000] {processor.py:186} INFO - Started process (PID=2517) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:18:36.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:18:36.280+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:18:36.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:18:36.329+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:18:36.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:18:36.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:18:36.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.109 seconds
[2025-04-01T18:19:06.851+0000] {processor.py:186} INFO - Started process (PID=2582) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:19:06.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:19:06.859+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:19:06.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:19:06.909+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:19:06.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:19:06.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:19:06.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.099 seconds
[2025-04-01T18:19:37.991+0000] {processor.py:186} INFO - Started process (PID=2650) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:19:37.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:19:37.998+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:19:37.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:19:38.044+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:19:38.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:19:38.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:19:38.084+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.102 seconds
[2025-04-01T18:20:08.302+0000] {processor.py:186} INFO - Started process (PID=2714) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:20:08.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:20:08.308+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:20:08.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:20:08.345+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:20:08.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:20:08.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:20:08.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.075 seconds
[2025-04-01T18:20:38.428+0000] {processor.py:186} INFO - Started process (PID=2776) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:20:38.430+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:20:38.433+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:20:38.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:20:38.457+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:20:38.453+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:20:38.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:20:38.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.058 seconds
[2025-04-01T18:21:09.723+0000] {processor.py:186} INFO - Started process (PID=2839) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:21:09.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:21:09.727+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:21:09.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:21:09.756+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:21:09.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:21:09.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:21:09.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.063 seconds
[2025-04-01T18:21:40.175+0000] {processor.py:186} INFO - Started process (PID=2903) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:21:40.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:21:40.179+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:21:40.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:21:40.204+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:21:40.199+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:21:40.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:21:40.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.063 seconds
[2025-04-01T18:22:10.720+0000] {processor.py:186} INFO - Started process (PID=2967) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:22:10.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:22:10.729+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:22:10.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:22:10.782+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:22:10.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:22:10.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:22:10.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.119 seconds
[2025-04-01T18:22:41.252+0000] {processor.py:186} INFO - Started process (PID=3035) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:22:41.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:22:41.260+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:22:41.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:22:41.292+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:22:41.287+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:22:41.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:22:41.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.080 seconds
[2025-04-01T18:23:11.831+0000] {processor.py:186} INFO - Started process (PID=3101) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:23:11.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:23:11.838+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:23:11.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:23:11.879+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:23:11.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:23:11.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:23:11.924+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.104 seconds
[2025-04-01T18:23:42.386+0000] {processor.py:186} INFO - Started process (PID=3168) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:23:42.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:23:42.393+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:23:42.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:23:42.456+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:23:42.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:23:42.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:23:42.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.153 seconds
[2025-04-01T18:24:12.808+0000] {processor.py:186} INFO - Started process (PID=3236) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T18:24:12.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T18:24:12.818+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:24:12.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:24:12.866+0000] {logging_mixin.py:190} INFO - [2025-04-01T18:24:12.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T18:24:12.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T18:24:12.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.124 seconds
[2025-04-01T19:40:10.432+0000] {processor.py:186} INFO - Started process (PID=4245) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:40:10.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:40:10.436+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:40:10.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:40:10.521+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:40:10.514+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:40:10.523+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:40:10.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.136 seconds
[2025-04-01T19:40:41.421+0000] {processor.py:186} INFO - Started process (PID=4310) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:40:41.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:40:41.424+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:40:41.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:40:41.454+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:40:41.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:40:41.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:40:41.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.062 seconds
[2025-04-01T19:41:12.125+0000] {processor.py:186} INFO - Started process (PID=4375) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:41:12.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:41:12.128+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:41:12.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:41:12.155+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:41:12.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:41:12.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:41:12.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.050 seconds
[2025-04-01T19:41:42.730+0000] {processor.py:186} INFO - Started process (PID=4440) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:41:42.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:41:42.733+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:41:42.733+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:41:42.757+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:41:42.752+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:41:42.760+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:41:42.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.053 seconds
[2025-04-01T19:42:13.283+0000] {processor.py:186} INFO - Started process (PID=4505) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:42:13.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:42:13.287+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:42:13.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:42:13.311+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:42:13.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:42:13.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:42:13.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.052 seconds
[2025-04-01T19:42:43.782+0000] {processor.py:186} INFO - Started process (PID=4570) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:42:43.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:42:43.785+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:42:43.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:42:43.812+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:42:43.806+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:42:43.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:42:43.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.053 seconds
[2025-04-01T19:43:13.913+0000] {processor.py:186} INFO - Started process (PID=4635) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:43:13.914+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:43:13.916+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:43:13.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:43:13.940+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:43:13.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:43:13.941+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:43:13.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.049 seconds
[2025-04-01T19:43:44.191+0000] {processor.py:186} INFO - Started process (PID=4700) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:43:44.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:43:44.194+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:43:44.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:43:44.222+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:43:44.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:43:44.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:43:44.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.057 seconds
[2025-04-01T19:44:14.644+0000] {processor.py:186} INFO - Started process (PID=4765) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:44:14.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:44:14.648+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:44:14.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:44:14.674+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:44:14.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:44:14.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:44:14.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.054 seconds
[2025-04-01T19:44:45.302+0000] {processor.py:186} INFO - Started process (PID=4831) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:44:45.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:44:45.306+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:44:45.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:44:45.333+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:44:45.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:44:45.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:44:45.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.055 seconds
[2025-04-01T19:45:15.784+0000] {processor.py:186} INFO - Started process (PID=4896) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:45:15.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:45:15.787+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:45:15.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:45:15.811+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:45:15.806+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:45:15.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:45:15.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.051 seconds
[2025-04-01T19:45:46.029+0000] {processor.py:186} INFO - Started process (PID=4961) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:45:46.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:45:46.033+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:45:46.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:45:46.057+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:45:46.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:45:46.059+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:45:46.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.051 seconds
[2025-04-01T19:46:16.210+0000] {processor.py:186} INFO - Started process (PID=5027) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:46:16.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:46:16.215+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:46:16.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:46:16.247+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:46:16.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:46:16.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:46:16.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.075 seconds
[2025-04-01T19:46:46.988+0000] {processor.py:186} INFO - Started process (PID=5092) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:46:46.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:46:46.991+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:46:46.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:46:47.017+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:46:47.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:46:47.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:46:47.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.051 seconds
[2025-04-01T19:47:17.241+0000] {processor.py:186} INFO - Started process (PID=5157) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:47:17.242+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:47:17.245+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:47:17.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:47:17.272+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:47:17.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:47:17.274+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:47:17.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.055 seconds
[2025-04-01T19:47:47.436+0000] {processor.py:186} INFO - Started process (PID=5222) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:47:47.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:47:47.439+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:47:47.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:47:47.461+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:47:47.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:47:47.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:47:47.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.042 seconds
[2025-04-01T19:48:17.649+0000] {processor.py:186} INFO - Started process (PID=5287) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:48:17.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:48:17.652+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:48:17.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:48:17.678+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:48:17.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:48:17.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:48:17.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.051 seconds
[2025-04-01T19:48:47.771+0000] {processor.py:186} INFO - Started process (PID=5352) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:48:47.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:48:47.775+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:48:47.775+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:48:47.800+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:48:47.795+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:48:47.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:48:47.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.051 seconds
[2025-04-01T19:49:18.396+0000] {processor.py:186} INFO - Started process (PID=5423) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:49:18.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:49:18.400+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:49:18.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:49:18.429+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:49:18.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:49:18.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:49:18.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.057 seconds
[2025-04-01T19:49:48.846+0000] {processor.py:186} INFO - Started process (PID=5488) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:49:48.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:49:48.850+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:49:48.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:49:48.876+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:49:48.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:49:48.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:49:48.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.054 seconds
[2025-04-01T19:50:19.434+0000] {processor.py:186} INFO - Started process (PID=5554) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:50:19.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:50:19.436+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:50:19.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:50:19.455+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:50:19.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:50:19.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:50:19.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.041 seconds
[2025-04-01T19:50:50.029+0000] {processor.py:186} INFO - Started process (PID=5619) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:50:50.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:50:50.032+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:50:50.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:50:50.053+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:50:50.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:50:50.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:50:50.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.045 seconds
[2025-04-01T19:51:20.431+0000] {processor.py:186} INFO - Started process (PID=5684) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:51:20.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:51:20.435+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:51:20.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:51:20.460+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:51:20.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:51:20.461+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:51:20.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.053 seconds
[2025-04-01T19:51:50.723+0000] {processor.py:186} INFO - Started process (PID=5749) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:51:50.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:51:50.728+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:51:50.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:51:50.754+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:51:50.749+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:51:50.755+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:51:50.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.058 seconds
[2025-04-01T19:52:21.001+0000] {processor.py:186} INFO - Started process (PID=5814) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:52:21.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:52:21.005+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:52:21.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:52:21.034+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:52:21.027+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:52:21.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:52:21.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.059 seconds
[2025-04-01T19:52:51.980+0000] {processor.py:186} INFO - Started process (PID=5879) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:52:51.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:52:51.984+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:52:51.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:52:52.011+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:52:52.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:52:52.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:52:52.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.055 seconds
[2025-04-01T19:53:22.795+0000] {processor.py:186} INFO - Started process (PID=5944) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:53:22.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:53:22.799+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:53:22.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:53:22.822+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:53:22.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:53:22.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:53:22.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.047 seconds
[2025-04-01T19:53:53.272+0000] {processor.py:186} INFO - Started process (PID=6009) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:53:53.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:53:53.280+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:53:53.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:53:53.331+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:53:53.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:53:53.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:53:53.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.114 seconds
[2025-04-01T19:54:24.251+0000] {processor.py:186} INFO - Started process (PID=6074) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:54:24.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:54:24.258+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:54:24.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:54:24.305+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:54:24.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:54:24.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:54:24.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.100 seconds
[2025-04-01T19:54:54.463+0000] {processor.py:186} INFO - Started process (PID=6139) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:54:54.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:54:54.470+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:54:54.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:54:54.531+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:54:54.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:54:54.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:54:54.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.129 seconds
[2025-04-01T19:55:25.624+0000] {processor.py:186} INFO - Started process (PID=6203) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:55:25.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:55:25.630+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:55:25.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:55:25.681+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:55:25.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:55:25.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:55:25.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.109 seconds
[2025-04-01T19:55:55.837+0000] {processor.py:186} INFO - Started process (PID=6268) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:55:55.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:55:55.843+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:55:55.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:55:55.890+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:55:55.880+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:55:55.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:55:55.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.111 seconds
[2025-04-01T19:56:26.369+0000] {processor.py:186} INFO - Started process (PID=6334) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:56:26.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:56:26.376+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:56:26.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:56:26.431+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:56:26.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:56:26.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:56:26.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.108 seconds
[2025-04-01T19:56:57.249+0000] {processor.py:186} INFO - Started process (PID=6399) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:56:57.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:56:57.256+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:56:57.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:56:57.309+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:56:57.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:56:57.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:56:57.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.120 seconds
[2025-04-01T19:57:27.462+0000] {processor.py:186} INFO - Started process (PID=6464) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:57:27.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:57:27.470+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:57:27.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:57:27.517+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:57:27.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:57:27.520+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:57:27.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.109 seconds
[2025-04-01T19:57:57.655+0000] {processor.py:186} INFO - Started process (PID=6529) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:57:57.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:57:57.663+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:57:57.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:57:57.702+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:57:57.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:57:57.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:57:57.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.098 seconds
[2025-04-01T19:58:27.869+0000] {processor.py:186} INFO - Started process (PID=6594) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:58:27.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:58:27.877+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:58:27.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:58:27.924+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:58:27.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:58:27.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:58:27.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.102 seconds
[2025-04-01T19:58:58.255+0000] {processor.py:186} INFO - Started process (PID=6659) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:58:58.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:58:58.264+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:58:58.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:58:58.322+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:58:58.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:58:58.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:58:58.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.127 seconds
[2025-04-01T19:59:28.546+0000] {processor.py:186} INFO - Started process (PID=6724) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:59:28.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:59:28.549+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:59:28.548+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:59:28.569+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:59:28.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:59:28.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:59:28.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.046 seconds
[2025-04-01T19:59:58.772+0000] {processor.py:186} INFO - Started process (PID=6779) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T19:59:58.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T19:59:58.776+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:59:58.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:59:58.809+0000] {logging_mixin.py:190} INFO - [2025-04-01T19:59:58.803+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T19:59:58.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T19:59:58.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.065 seconds
[2025-04-01T20:00:30.182+0000] {processor.py:186} INFO - Started process (PID=6841) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:00:30.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:00:30.186+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:00:30.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:00:30.207+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:00:30.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:00:30.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:00:30.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.049 seconds
[2025-04-01T20:01:01.938+0000] {processor.py:186} INFO - Started process (PID=6905) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:01:01.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:01:01.942+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:01:01.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:01:01.979+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:01:01.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:01:01.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:01:02.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.071 seconds
[2025-04-01T20:01:32.265+0000] {processor.py:186} INFO - Started process (PID=6967) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:01:32.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:01:32.270+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:01:32.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:01:32.300+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:01:32.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:01:32.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:01:32.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.063 seconds
[2025-04-01T20:02:02.864+0000] {processor.py:186} INFO - Started process (PID=7022) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:02:02.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:02:02.869+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:02:02.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:02:02.904+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:02:02.897+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:02:02.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:02:02.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.083 seconds
[2025-04-01T20:02:33.714+0000] {processor.py:186} INFO - Started process (PID=7083) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:02:33.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:02:33.719+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:02:33.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:02:33.749+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:02:33.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:02:33.750+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:02:33.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.062 seconds
[2025-04-01T20:03:04.242+0000] {processor.py:186} INFO - Started process (PID=7144) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:03:04.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:03:04.246+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:03:04.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:03:04.273+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:03:04.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:03:04.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:03:04.299+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.065 seconds
[2025-04-01T20:03:34.691+0000] {processor.py:186} INFO - Started process (PID=7207) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:03:34.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:03:34.700+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:03:34.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:03:34.750+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:03:34.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:03:34.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:03:34.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.114 seconds
[2025-04-01T20:04:05.388+0000] {processor.py:186} INFO - Started process (PID=7273) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:04:05.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:04:05.396+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:04:05.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:04:05.449+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:04:05.439+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:04:05.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:04:05.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.122 seconds
[2025-04-01T20:04:35.798+0000] {processor.py:186} INFO - Started process (PID=7338) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:04:35.802+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:04:35.807+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:04:35.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:04:35.858+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:04:35.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:04:35.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:04:35.898+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.111 seconds
[2025-04-01T20:05:05.995+0000] {processor.py:186} INFO - Started process (PID=7403) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:05:05.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:05:06.002+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:05:06.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:05:06.050+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:05:06.040+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:05:06.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:05:06.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.103 seconds
[2025-04-01T20:05:36.461+0000] {processor.py:186} INFO - Started process (PID=7468) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:05:36.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:05:36.469+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:05:36.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:05:36.516+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:05:36.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:05:36.519+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:05:36.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.105 seconds
[2025-04-01T20:06:07.062+0000] {processor.py:186} INFO - Started process (PID=7533) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:06:07.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:06:07.070+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:06:07.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:06:07.130+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:06:07.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:06:07.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:06:07.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.129 seconds
[2025-04-01T20:06:38.184+0000] {processor.py:186} INFO - Started process (PID=7598) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:06:38.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:06:38.193+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:06:38.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:06:38.251+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:06:38.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:06:38.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:06:38.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.125 seconds
[2025-04-01T20:07:09.083+0000] {processor.py:186} INFO - Started process (PID=7663) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:07:09.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:07:09.090+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:07:09.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:07:09.145+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:07:09.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:07:09.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:07:09.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.131 seconds
[2025-04-01T20:07:40.294+0000] {processor.py:186} INFO - Started process (PID=7728) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:07:40.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:07:40.304+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:07:40.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:07:40.356+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:07:40.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:07:40.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:07:40.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.115 seconds
[2025-04-01T20:08:10.794+0000] {processor.py:186} INFO - Started process (PID=7793) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:08:10.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:08:10.800+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:08:10.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:08:10.849+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:08:10.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:08:10.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:08:10.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.111 seconds
[2025-04-01T20:08:41.264+0000] {processor.py:186} INFO - Started process (PID=7858) to work on /opt/airflow/dags/pipeline1.py
[2025-04-01T20:08:41.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/pipeline1.py for tasks to queue
[2025-04-01T20:08:41.271+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:08:41.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:08:41.320+0000] {logging_mixin.py:190} INFO - [2025-04-01T20:08:41.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/pipeline1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/pipeline1.py", line 7, in <module>
    from models.prompts import ollama_connect, pattern_recognition, anomaly_detection
  File "/opt/airflow/dags/models/prompts.py", line 1, in <module>
    from langchain_ollama import ChatOllama
ModuleNotFoundError: No module named 'langchain_ollama'
[2025-04-01T20:08:41.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/pipeline1.py
[2025-04-01T20:08:41.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/pipeline1.py took 0.114 seconds
